### ISSUE TITLE
Customizeable month title format

### ISSUE THREAD

**Issue by mkharibalaji** [wix/react-native-calendars#121] opened 2017-08-01 01:18 UTC
Hi,
   Great Piece of work!!!. Something like '<Mon> <Year>' in agenda and CalendarList would be a great feature.

![screen shot 2017-08-01 at 6 46 03 am](https://user-images.githubusercontent.com/5992474/28805128-61e8e310-7685-11e7-87c7-0ba952fe1038.png)

**Comment by tautvilas** [comment] 2017-08-03 06:40
Please use `monthFormat={'yyyy MM'}` property

**Comment by mkharibalaji** [comment] 2017-08-04 01:10
@tautvilas 
        Thank you.Does monthFormat Prop display the Month & Year when the week alone is displayed as in Agenda ? That is what is am referring to and not when the Calendar is expanded.
Please correct me if i am wrong.

**Comment by tautvilas** [comment] 2017-08-08 06:29
Yes, agenda does not support this yet. I am closing this as duplicate of #132

**Closed by tautvilas** 2017-08-08 06:29 UTC
Labels: enhancement

**Comment by ManishPrakharan** [comment] 2021-02-15 06:51
On Changing date months title of date does not changes. As I have the string '15 Feb 2021' so when I change the date the date does not change it remains '15 Feb 2021. Please help!
