### ISSUE TITLE
Feature request: Reverse scrolling for historical events

### ISSUE THREAD

**Issue by johra** [wix/react-native-calendars#206] opened 2017-10-17 06:57 UTC
## Description

I would like to be able to reverse the scrolling, this would enable the use of an overview of historical dates and events.

## Expected Behavior

When scrolling up, it would go back to previous weeks/months. When scroll down to current date it would either stop or continue forward as today.

**Comment by tautvilas** [comment] 2018-02-01 12:30
Duplicate of #259

**Closed by tautvilas** 2018-02-01 12:30 UTC
Labels: enhancement
