### ISSUE TITLE
CalendarList blank on initial load (RN 0.47.1)

### ISSUE THREAD

**Issue by ultralol** [wix/react-native-calendars#135] opened 2017-08-11 14:48 UTC
When CalendarList is used it displays month label for the first moments (I guess it's load time), then turns to blank **untill** I drag it, when being dragged it updates to normal instantly

Calendar works fine however, issue only for CalendarList

I think it is not updated properly after month data is loaded

Issue observed after updating RN from 0.46.4 to 0.47.1

Platform: Android (both emulator/API_23 and device/Nexus6)
node v: 6.10.2
npm v: 4.6.1
react-native v: 0.47.1
react-native-calendars v: 1.5.6

Any ideas how to fix or workaround to avoid blank state?

**Comment by dmitriy-shmilo** [comment] 2017-08-13 10:23
Came to report this exact issue. Happens on Android API 23 emulator and physical device. Doesn't happen on iOS 10.3 simulator. Also, calendar list takes forever (several seconds) to load on Android.

**Comment by tautvilas** [comment] 2017-08-14 06:46
Hi, thx for bug report. As I understand new version of RN broke some backwards compatibility. I will try to solve this issue this week.

**Comment by ultralol** [comment] 2017-08-14 10:23
@dmitriy-shmilo 
> Also, calendar list takes forever (several seconds) to load on Android.
A bit off topic but this takes a lot of time in debug mode, release is much faster

**Comment by tautvilas** [comment] 2017-08-15 19:35
Started checking issues with 0.47.1. I also get red screens on IOS:
```
Module JSTimersExecution is not a registered callable module (calling callTimers)

__callFunction
    MessageQueue.js:257:6
<unknown>
    MessageQueue.js:103:26
__guard
    MessageQueue.js:231:6
callFunctionReturnFlushedQueue
    MessageQueue.js:102:17
```

Maybe somebody got idea what could cause this?

**Comment by tautvilas** [comment] 2017-08-16 18:05
Apparently RN 0.47.1 is broken, it displays JSTimersExecution errors even on clean projects in IOS

**Comment by wake-up-neo** [comment] 2017-08-21 22:39
The same for iOS. CalendarList is blank before drag

**Comment by felixaa** [comment] 2017-09-13 07:43
Any updates on this?

**Comment by felixaa** [comment] 2017-09-13 10:13
I had my CalendarList in a tab using React-Navigation's tab-navigator: Blank. Tested by moving it to a seperate screen outside the tab-navigator: Not blank. Enabled lazy rendering of tabs as opposed to rendering them upfront: Not Blank!

This fixed it for me!

RN version: 0.48.3
react-native-calendars version: 1.5.8

**Comment by tautvilas** [comment] 2017-09-14 12:23
Fixed in 1.6.0

**Closed by tautvilas** 2017-09-14 12:23 UTC
Labels: bug

**Comment by benevbright** [comment] 2018-01-15 12:20
It doesn't seem to be fixed. 

I'm seeing the same bug, today's react-native version, which is 0.52.0.
Only occurs in Android.

Anyone?

**Comment by tautvilas** [comment] 2018-01-15 12:25
what navigation library are you using? can you reproduce this bug in example project?

**Comment by benevbright** [comment] 2018-01-15 12:26
I don't even use navigation, but a just plain react-native app with one CalendarList.

**Comment by tautvilas** [comment] 2018-01-15 12:28
Could be some breaking change introduced by RN 0.52.0, I did not test on this version. Can you record video/gif how it looks? Is it completely blank? Did you set flex:1 on container?

**Comment by benevbright** [comment] 2018-01-15 12:30
It is completely blank at the beginning but since I try to scroll, it shows. 
It's same with the current issue.
So 'flex:1' doesn't matter I think.

**Comment by tautvilas** [comment] 2018-01-15 12:35
I created a new issue for this #302

**Comment by benevbright** [comment] 2018-01-15 12:41
Thanks. I attached a video clip in that issue.
