### ISSUE TITLE
calendar breaks in android apk or "expo start --no-dev --minify", but works otherwise

### ISSUE THREAD

**Issue by Settao** [wix/react-native-calendars#1335] opened 2020-11-29 08:35 UTC
## Description

v1.491.0 calendar breaks in android apk or "expo start --no-dev --minify", but works otherwise.  This happened when the calendar needs to show some dots on the date cell it seemed.

## Expected Behavior

The calendar should work in both development and production mode.

## Observed Behavior

When the markedDates field contains some "multi-dot" for the month, it will crash in android apk or "expo start --no-dev --minify".  It will work if I use the --no-minify option.  This together with the Android Studio Simulator log message (see below) suggests that it is likely due to some sort of module(s) dependencies not being done properly during minification.  

```
_11-29 14:56:00.340 10135  7263  7419 E ReactNativeJS: Error: Requiring unknown module "undefined"._
```

## Environment

* `yarn list react-native-calendars`: react-native-calendars@1.491.0
* `yarn list react-native`: react-native@0.61.4

Please run these commands in the project folder and fill in their results:

  Expo CLI 4.0.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: 1.5.13 => 1.5.13
    Expo Workflow: managed

Also specify:

Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283

**Comment by Settao** [comment] 2020-11-29 08:35
Stuck a few days already.  Please help!!

**Comment by emilisb** [comment] 2020-11-30 10:34
Hi, we will investigate.

**Comment by emilisb** [comment] 2020-11-30 15:18
I tested the`Calendar` with `multi-dot` on Expo 39, it works fine on both iOS and Android with `expo start --no-dev --minify`. Make sure the error is not in your code. If you still think the problem is caused by React Native Calendars, please make a small reproducible example.

**Comment by Settao** [comment] 2020-11-30 15:36
Thanks for the feedback!  I forgot to update this post as I am suspecting axios or something related to the asynch caalling.  But I am not ruling out the calendar yet, because my expo version is only 37 upgraded from 2X.  So, there are a lot of things moved.  I will keep you posted.

**Comment by Settao** [comment] 2020-12-07 14:49
Finally, it is actually the following component being the culprit.  Excluding it, everything works.  I suspect it is the relative path issue.  Likely the minify option somehow loses the handle during run.  Any pointers to fix this saving me further R&D time? 

As for the Calendar, I think this can be close.  It works just fine.

{ (this.state.markedDates?(JSON.stringify(this.state.markedDates).search("color") <0):true) &&
(

          <View style={styles.ad_row}>
            <Image
              source={require('../../../assets/media/images/ad_banner_1.jpg')}
              style={{height:120*vh, width: 710*vw, marginLeft: 5*vw, marginRight: 5*vw, marginTop: 10*vh}}
            />
          </View>
          )}
        </View>

**Comment by Settao** [comment] 2020-12-09 09:07
While I am not sure if this is related to the calendar, because of the three important observations below, I am putting the workaround here anyways:

1. The Image component works for most rendering/re-rendering. It will only break after the Calendar render dots on the days.

2. I have narrowed down the true cause of the problem down to the “source” attribute of the Image component. If I use:

source={ {uri:‘http://www.settao.com/wp-content/uploads/2017/07/it2.png’}}, then it will work.

3. I tried placing the image in the same directory as the screen component, and it still failed.
Since my ultimate intent is to use uri, S3, CDN, etc to store such more static images, the solution works for me.

While I’d love to help drill down deeper into this clearly Expo/React Native bug, but because of confidentiality and security reasons, I cannot disclose even the skeleton of the code.

For those who have encountered this problem and try to resolve using babel-plugin-module-resolver, please de-prioritize such approach, because of the 3 observations mentioned above.

Good luck!

**Comment by emilisb** [comment] 2020-12-09 09:09
It sounds like you have an issue with your bundler and it doesn't bundle your images into release app properly.

I'm closing the issue since it's not related to Calendars, thanks for the update!

**Closed by emilisb** 2020-12-09 09:09 UTC
Labels: Bug report, Needs more info

**Comment by agungsb** [comment] 2021-12-28 07:45
This happens to me on Expo 44 and expo-cli@5.0.3 when I try to run:

```expo start:web --no-dev --minify```

This even happens in the fresh expo app.

Is there any thought?
