### ISSUE TITLE
Marked dates display a vertical white line through them on Android

### ISSUE THREAD

**Issue by hannigand** [wix/react-native-calendars#158] opened 2017-08-25 15:11 UTC
## Description

When selecting dates with the Calendar component, some of the marked dates have a white vertical liine through them. 

See the tile representing 5th August

![screen shot 2017-08-25 at 15 57 25](https://user-images.githubusercontent.com/5614282/29719650-e2f495c6-89ae-11e7-9c11-ff9b94190f68.png)

## Expected Behavior

I simulated a date selection from Aug 1st - Aug 25th. It is expected that all tiles render without a vertical line through it.

## Observed Behavior

A single date has a vertical line through it. After testing this in two separate repositories, the problematic date was Aug 5th, is this a coincidence? 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  1.5.8
* `npm ls react-native`: 0.44.0 (& 0.45.1)

Also specify:

1. Phone/emulator/simulator & version: Nexus 6P, Android 7.0 (Marshmellow), API 24 

## Reproducible Demo

Repo: https://github.com/hannigand/react-native-calendars

Steps:
1. `cd example`
2. `yarn install`
3. `react-native run-android`
4. Navigate to the `Calendar` tab
5. Observe the first Calendar

**Comment by JCMais** [comment] 2017-09-01 20:39
Same issue here

**Comment by tautvilas** [comment] 2017-09-14 12:34
Same as #61

**Comment by JCMais** [comment] 2017-09-14 12:42
This is caused by the margins on the calendar wrapper, removing them fix the issue.

**Comment by tautvilas** [comment] 2017-09-14 12:52
@JCMais could you elaborate? Thanks

**Comment by hannigand** [comment] 2017-09-27 10:03
Poke @tautvilas please could you review pull request.

**Comment by tautvilas** [comment] 2017-09-28 07:05
Reviewed and merged

**Closed by tautvilas** 2017-09-28 07:05 UTC
Labels: bug
