### ISSUE TITLE
Hard coded font weight applied on month text

### ISSUE THREAD

**Issue by SukhKalsi** [wix/react-native-calendars#139] opened 2017-08-15 11:07 UTC
I'm trying to use a custom font however there is a hard coded font weight applied to the `monthText` as shown here: https://github.com/wix/react-native-calendars/blob/master/src/calendar/header/style.js#L17

Is there a reason for this? Happy to create a PR to resolve this but would like to know where we want to go with this i.e. shall we remove this completely or should this be an option in a prop that can be passed through?

Currently using this in `CalendarList` component.

**Comment by tautvilas** [comment] 2017-08-17 11:25
hi, thanks for feedback, I will be closing this as duplicate of #100 please add your ideas there

**Closed by tautvilas** 2017-08-17 11:25 UTC
