### ISSUE TITLE
Divider in the middle of the date in set of markedDates

### ISSUE THREAD

**Issue by valerybodak** [wix/react-native-calendars#61] opened 2017-06-14 08:23 UTC
I have issue with divider in the middle of the date in set of markedDates. Please see attach.

![bug](https://user-images.githubusercontent.com/26433088/27122303-f7cb0826-50f2-11e7-9835-58ca1d799f4e.png)

This is my markedDates:

markedDates={
                                {'2012-05-20': [{textColor: 'green'}],
                                 '2017-06-07': [{startingDay: true,  color: '#d4ff2a', textColor: 'black'}],
                                 '2017-06-08': [{color: '#d4ff2a', textColor: 'black'}],
                                 '2017-06-09': [{color: '#d4ff2a', textColor: 'black'}],
                                 '2017-06-10': [{color: '#d4ff2a', textColor: 'black'}],
                                 '2017-06-11': [{endingDay: true, color: '#d4ff2a', textColor: 'black'}],
                                 '2017-06-20': [{startingDay: true, color: '#d4ff2a', textColor: 'black'}, {endingDay: true, color: '#d4ff2a', textColor: 'black'}]
                                }
                            }

My version is:
**"react-native-calendars": "^1.4.0",**

I have found temporary fix by adding **marginRight: -1** and **marginLeft: -1** for styles **leftFiller** and **rightFiller** in _\node_modules\react-native-calendars\src\calendar\day\interactive\style.js_

leftFiller: {
      height: FILLER_HEIGHT,
      flex: 1,
      **marginRight: -1**
    },
    rightFiller: {
      height: FILLER_HEIGHT,
      flex: 1,
      **marginLeft: -1**
    },

But could you please address this issue in the next releases.
Thank you.

**Comment by tautvilas** [comment] 2017-07-13 09:26
Could specify on what device/simulator did you try the code? (could not reproduce on iphone 6 simulator)

**Comment by tautvilas** [comment] 2017-07-13 09:29
Could not reproduce on iphone 7plus simulator either, could you try to check if this is still reproduceable with latest version with react-native-calendars? thanks!

**Comment by tautvilas** [comment] 2017-07-13 09:30
Sorry, saw that you were testing on android, will check

**Comment by tautvilas** [comment] 2017-07-13 09:35
Could not reproduce on google nexus 5 simulator. If you can reproduce this bug with latest calendars and react-native versions plz give more info about exact version of phone model + RN version, otherwise I will be closing this issue (maybe it was a bug of certain old react native version).

**Closed** 2017-07-24 06:55 UTC
Labels: bug

**Comment by CptFabulouso** [comment] 2017-08-03 18:02
I have the same problem
running on physical device Nexus 5x
react-native version: 0.46.4,
react-native-calendars version: 1.5.6

I have noticed this 1px wide stripe in my projects before, it appears between views next to each other with no apparent reason, so I guess in the number 9 date two views meet. I think it has something to do with how react calculates layout and I guess due to rounding error this 1px stripe appears, but that's just total guess. I usually solve this issue by giving background color to the parent view, so the stripe blends in, but that can't be used here. The only bullet proof method I can think of would be creating the whole date marking as one view.
