### ISSUE TITLE
Starting day and ending day styling issue

### ISSUE THREAD

**Issue by ws7one** [wix/react-native-calendars#744] opened 2019-02-22 08:40 UTC
## Description

The starting day and endiing day in the calendar is not consistent with expected design. I get rounded borders sometimes and sometimes i dont

## Expected Behavior

<Calendar
current={getDateForCalendar(fromDate)}
maxDate={getDateForCalendar(new Date())}
onDayPress={this.setCustomFromToDates}
monthFormat={'MMMM yyyy'}
hideExtraDays={false}
hideDayNames={false}
markingType={'period'}
markedDates={getAllDatesBetween(fromDate, toDate)}
/>

As the name suggests, i get all days between 2 days in the following format
{
    "2019-02-01": {
        "startingDay": true,
        "color": "#FD2F40",
        "textColor": "white"
    },
    "2019-02-02": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-03": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-04": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-05": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-06": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-07": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-08": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-09": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-10": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-11": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-12": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-13": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-14": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-15": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-16": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-17": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-18": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-19": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-20": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-21": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-02-22": {
        "endingDay": true,
        "color": "#FD2F40",
        "textColor": "white"
    }
}

The result I get is as follows and it is expected:
![calendarcorrect](https://user-images.githubusercontent.com/41139390/53229045-2040c780-36a9-11e9-91cd-1b62fb9ad1e4.PNG)

## Observed Behavior

After this is where the problem begins.
Now when I want to change the range, I do this. Lets say I move to January 2019 and click 14th Jan, the following is the result

getAllDatesBetween returns
{
    "2019-01-14": {
        "startingDay": true,
        "color": "#FD2F40",
        "textColor": "white"
    }
}
![image](https://user-images.githubusercontent.com/41139390/53229165-89c0d600-36a9-11e9-93eb-b1737f00a582.png)

After this i click the end date, lets say 24th Jan
getAllDatesBetween returns
{
    "2019-01-14": {
        "startingDay": true,
        "color": "#FD2F40",
        "textColor": "white"
    },
    "2019-01-15": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-16": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-17": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-18": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-19": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-20": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-21": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-22": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-23": {
        "color": "#969696",
        "textColor": "white"
    },
    "2019-01-24": {
        "endingDay": true,
        "color": "#FD2F40",
        "textColor": "white"
    }
}

and it looks like this
![image](https://user-images.githubusercontent.com/41139390/53229241-bd036500-36a9-11e9-90aa-169da2e87551.png)

I don't see why the start and end dates design changes. What happens to the rounded corners?

There are a few other inconsistent behaviors I have noticed as follow:
![image](https://user-images.githubusercontent.com/41139390/53229335-f0de8a80-36a9-11e9-9996-f9fb629ef88f.png)

![image](https://user-images.githubusercontent.com/41139390/53229364-ffc53d00-36a9-11e9-9715-24781e341b75.png)

![image](https://user-images.githubusercontent.com/41139390/53229383-0bb0ff00-36aa-11e9-8815-8915b8b3d770.png)

**### An interesting behavior I have noticed in my calendar is that the rounded corner work perfectly only for the 1st and 4th fridays**

Also what my end goal here is to style the calendar as follows
![group 2660](https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png)

you can ignore the arrow and title positions, I like it the way it is now.
I am mainly insterested in the range design. Is it possible? if so how?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
No error
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.22.0
* `npm ls react-native`: react-native@0.57.3

Also specify:

1. Phone/emulator/simulator & version: Android Emulator Android 9.0 API 28

## Reproducible Demo

```
<Calendar
current={getDateForCalendar(fromDate)}
maxDate={getDateForCalendar(new Date())}
onDayPress={this.setCustomFromToDates}
monthFormat={'MMMM yyyy'}
hideExtraDays={false}
hideDayNames={false}
markingType={'period'}
markedDates={getAllDatesBetween(fromDate, toDate)}
/>

const getDateForCalendar = (date) => {
    const yr = date.getFullYear();
    const month = `${date.getMonth() + 1 < 10 ? 0 : ''}${date.getMonth() + 1}`;
    const d = `${date.getDate() < 10 ? 0 : ''}${date.getDate()}`;
    return `${yr}-${month}-${d}`;
};

const getAllDatesBetween = (fromDate, toDate) => {
    console.log('[MANews][getAllDatesBetween]fromDate', getDateForCalendar(fromDate));
    if (toDate) console.log('[MANews][getAllDatesBetween]toDate', getDateForCalendar(toDate));

    let curDate = new Date(fromDate.getTime());
    const datesForCalendar = {};
    datesForCalendar[getDateForCalendar(fromDate)] = {
        startingDay: true,
        color: '#FD2F40',
        textColor: 'white'
    };
    if (toDate) {
        while (curDate < toDate) {
            curDate = new Date(curDate.setDate(curDate.getDate() + 1));
            datesForCalendar[getDateForCalendar(curDate)] = {
                color: '#969696',
                textColor: 'white'
            };
        }
        datesForCalendar[getDateForCalendar(toDate)] = {
            endingDay: true,
            color: '#FD2F40',
            textColor: 'white'
        };
    }
    console.log('[MANews][getAllDatesBetween]datesForCalendar', JSON.stringify(datesForCalendar));

    return datesForCalendar;
};
```

**Comment by AlexanderBalson** [comment] 2019-02-27 04:37
I have an app that crashes when running on Android, and it's doing something similar with random inconsistent styling. For me it also has fatal errors with the error message being simply `backgroundColor` which is very helpful :joy: Have you had any crashes from styling during your issues?

**Comment by ws7one** [comment] 2019-02-27 06:46
I haven't had crashes with these.. just styling issues.
Whats the full error message you are getting? Are you applying `backgroundColor`?

**Comment by AlexanderBalson** [comment] 2019-02-27 11:02
Much of the app has background colours set and they work fine on Android, but the inconsistent behaviour of starting/ending dates in the  `period` style of calendarlist (often it doesn't add the rounded sides), and the fact that the error comes from these `markedDates` being manipulated makes me think it must come from the way the `color` value of `markedDates` days is applying a background colour to the days.

I haven't tried it for a couple of days, but basically the full error message just started with `backgroundColor` and then listed other scripts that seemed to be compiled, they weren't anything I'd written. I may give it another go tomorrow, if anything just to see the strange error output.

**Comment by AlexanderBalson** [comment] 2019-02-28 02:21
Ran the app through expo on Android today, and got this error:
```
Uncaught Error: backgroundColor

12:18:14 Fatal Error
```

On Android now the starting/ending days are not showing the curved borders at all, and the error occurs when onDayPress is fired, where the colour of the day in question changes.

**Comment by deepaksharma33** [comment] 2019-03-04 07:44
Facing the same problem. Any solutions?

**Comment by deepaksharma33** [comment] 2019-03-04 12:48
For the time being, unless it gets fixed I am using the following workaround, I hope it helps!!

In your file **node_modules/react-native-calendars/src/calendar/day/period/index.js**

replace or comment the return() section inside render() function and add the following lines - 

const { startingDay, endingDay} = this.props.marking;
    return (
      <TouchableWithoutFeedback onPress={this.onDayPress}>
        <View style={this.style.wrapper}>
          {fillers}
          {
            ( startingDay || endingDay) ? (
              <View>
                <Text style={[
                  textStyle, 
                  containerStyle,
                  {paddingVertical: 7, textAlign: 'center', marginTop: 0}
                ]}>
                  {String(this.props.children)}
                </Text>
              </View>
            ) : (
              <View style={containerStyle}>
                <Text style={textStyle}>{String(this.props.children)}</Text>
              </View>
            )
          }
        </View>
      </TouchableWithoutFeedback>
    );

and then you are Good to Go!!!

**Comment by ws7one** [comment] 2019-03-14 12:35
Interestingly, this works perfectly fine on iOS.

**Comment by lilyxl8** [comment] 2019-03-25 16:13
This is a duplicate of #642, for which there is a PR #728 open.
Can we close?

**Comment by vuhoangp** [comment] 2019-09-09 10:13
I've same problem ...
and i think this isn't duplicate of #642.
[https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png](url)
^ Anyone can tell me how can do it ?

**Comment by vuhoangp** [comment] 2019-09-09 10:16
I've same problem ...
and i think this isn't duplicate of #642.
![](https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png)
^ Anyone can tell me how can do it ?

**Comment by vuhoangp** [comment] 2019-09-09 10:50
I want to  make a calendar like you 
![](https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png)
But when i run your Reproducible Demo , result is 
![Screen Shot 2019-09-09 at 5 48 50 PM](https://user-images.githubusercontent.com/51758366/64525069-356e0280-d32a-11e9-9b04-7c7e42b4f07f.png)
Can you show me your source code pls?

**Comment by ggola** [comment] 2020-05-09 04:27
> For the time being, unless it gets fixed I am using the following workaround, I hope it helps!!
> 
> In your file **node_modules/react-native-calendars/src/calendar/day/period/index.js**
> 
> replace with or comment the return() section inside render() function and add the following lines -
> 
> ```
> return (
>       <TouchableWithoutFeedback onPress={this.onDayPress}>
>         <View style={this.style.wrapper}>
>           {fillers}
>           <View>
>             <Text style={[textStyle, containerStyle]}>{String(this.props.children)}</Text>
>           </View>
>         </View>
>       </TouchableWithoutFeedback>
>     );
> ```
> 
> in the above code only the style object for the View containing the Text component has been added to the Text component and removed from the View component.
> 
> and also in your **node_modules/react-native-calendars/src/calendar/day/period/style.js** file modify the
> **text** object as following -
> 
> **remove -**
> `marginTop: 7,`
> 
> **and add -**
> `paddingTop: 7, `
> `textAlign: 'center'`
> 
> and then you are Good to Go!!!
> 
> The original logic written to return the component of a single (Day) is correct but for some reason sometimes the component is not getting rendered on the screen with proper styles applied.

Awesome workaround: for me the rendering in iOS got wrong though (looking like the one in Android before the fix with not-rounded edges). In the index.js file I had to add the Platform API in the imports and just use conditional rendering. style.js remains edited as suggested.


```
{Platform.OS === 'android' ?
            <View>
              <Text allowFontScaling={false} style={[textStyle, containerStyle]}>{String(this.props.children)}</Text>
            </View>
          :
            <View style={containerStyle}>
              <Text allowFontScaling={false} style={textStyle}>{String(this.props.children)}</Text>
            </View>
          }

```

**Closed** 2020-06-12 16:35 UTC

**Comment by senturatechnologies** [comment] 2020-07-25 10:08
> I want to make a calendar like you
> ![](https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png)
> But when i run your Reproducible Demo , result is
> ![Screen Shot 2019-09-09 at 5 48 50 PM](https://user-images.githubusercontent.com/51758366/64525069-356e0280-d32a-11e9-9b04-7c7e42b4f07f.png)
> Can you show me your source code pls?

finally found a solution. but have to modify the node modules, so remember to add the changes to read me. then others can also use those.

go to the this file. 
**node_modules/react-native-calendars/src/calendar/day/period/index.js**

comment below lines.

    filters = (
    ....
    )

add below lines.

            const customStyles = {
            dayStyles: {backgroundColor: '#BEB1D7',width: 20,height: 
              26,position:'absolute'}
           }
           fillers = (
            <View style={[this.style.fillers, fillerStyle]}>
              {this.props.marking.endingDay ?<View style={customStyles.dayStyles}></View> 
              : null}
    
              <View style={[this.style.leftFiller, leftFillerStyle]}/>
              <View style={[this.style.rightFiller, rightFillerStyle]}/>
    
              {this.props.marking.startingDay ?<View style={[customStyles.dayStyles, 
               {marginLeft: 15}]}></View> : null}
            </View>
          );

note that `customStyles` you can edit.

the **node_modules** related phases now finish.

now move to your calendar component and override the styles of original calendar using their advanced styling guide. i did as mentioned below.

   

    calendarTheme = { 
             'stylesheet.day.period': {
                wrapper: {
                    alignItems: 'center',
                    alignSelf: 'stretch',
                    marginLeft: -2,
                    borderRadius: 2,
                    overflow: 'hidden'
                },
                leftFiller: {
                    height: 26,
                    flex: 1,
                    marginLeft: 50
                }
            }
    }

**Comment by jaikantshikray** [comment] 2024-02-25 16:39
this is not working with latest version 

> > I want to make a calendar like you
> > ![](https://user-images.githubusercontent.com/41139390/53229527-72ceb380-36aa-11e9-87fd-1ef271655f05.png)
> > But when i run your Reproducible Demo , result is
> > ![Screen Shot 2019-09-09 at 5 48 50 PM](https://user-images.githubusercontent.com/51758366/64525069-356e0280-d32a-11e9-9b04-7c7e42b4f07f.png)
> > Can you show me your source code pls?
> 
> finally found a solution. but have to modify the node modules, so remember to add the changes to read me. then others can also use those.
> 
> go to the this file. **node_modules/react-native-calendars/src/calendar/day/period/index.js**
> 
> comment below lines.
> 
> ```
> filters = (
> ....
> )
> ```
> 
> add below lines.
> 
> ```
>         const customStyles = {
>         dayStyles: {backgroundColor: '#BEB1D7',width: 20,height: 
>           26,position:'absolute'}
>        }
>        fillers = (
>         <View style={[this.style.fillers, fillerStyle]}>
>           {this.props.marking.endingDay ?<View style={customStyles.dayStyles}></View> 
>           : null}
> 
>           <View style={[this.style.leftFiller, leftFillerStyle]}/>
>           <View style={[this.style.rightFiller, rightFillerStyle]}/>
> 
>           {this.props.marking.startingDay ?<View style={[customStyles.dayStyles, 
>            {marginLeft: 15}]}></View> : null}
>         </View>
>       );
> ```
> 
> note that `customStyles` you can edit.
> 
> the **node_modules** related phases now finish.
> 
> now move to your calendar component and override the styles of original calendar using their advanced styling guide. i did as mentioned below.
> 
> ```
> calendarTheme = { 
>          'stylesheet.day.period': {
>             wrapper: {
>                 alignItems: 'center',
>                 alignSelf: 'stretch',
>                 marginLeft: -2,
>                 borderRadius: 2,
>                 overflow: 'hidden'
>             },
>             leftFiller: {
>                 height: 26,
>                 flex: 1,
>                 marginLeft: 50
>             }
>         }
> }
> ```
